ALTER TABLE `DEVICE` 
ADD COLUMN `fk_user` VARCHAR(255) NULL AFTER `token`;

ALTER TABLE `DEVICE` 
ADD INDEX `FK_DEVICE_fk_user_idx` (`fk_user` ASC);

ALTER TABLE `DEVICE` 
ADD CONSTRAINT `FK_DEVICE_fk_user`
  FOREIGN KEY (`fk_user`)
  REFERENCES `USER` (`id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;

ALTER TABLE `PLANTAO` 
DROP FOREIGN KEY `FK_PLANTAO_fk_solicitacao_Mudanca`,
DROP FOREIGN KEY `FK_PLANTAO_fk_agenda`;

ALTER TABLE `PLANTAO` 
DROP INDEX `FK_PLANTAO_fk_agenda` ,
DROP INDEX `FK_PLANTAO_fk_solicitacao_Mudanca` ;

ALTER TABLE `SOLICITACAO_MUDANCA` 
ADD COLUMN `fk_agenda` VARCHAR(255) NOT NULL AFTER `fk_horario_Escala`,
ADD COLUMN `fk_medico_solic` VARCHAR(255) NOT NULL AFTER `fk_agenda`,
ADD COLUMN `fk_medico_dest` VARCHAR(255) NOT NULL AFTER `fk_medico_solic`;

ALTER TABLE `SOLICITACAO_MUDANCA` 
DROP FOREIGN KEY `FK_SOLICITACAO_MUDANCA_fk_horario_Escala`;

ALTER TABLE `SOLICITACAO_MUDANCA` 
ADD INDEX `FK_AGENDA_fk_agenda_idx` (`fk_agenda` ASC),
ADD INDEX `FK_MEDICO_fk_medico_solic_idx` (`fk_medico_solic` ASC),
ADD INDEX `FK_MEDICO_fk_medico_dest_idx` (`fk_medico_dest` ASC);

ALTER TABLE `SOLICITACAO_MUDANCA` 
ADD CONSTRAINT `FK_SOLICITACAO_MUDANCA_fk_horario_Escala`
  FOREIGN KEY (`fk_horario_Escala`)
  REFERENCES `HORARIO_ESCALA` (`id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
ADD CONSTRAINT `FK_AGENDA_fk_agenda`
  FOREIGN KEY (`fk_agenda`)
  REFERENCES `AGENDA` (`id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
ADD CONSTRAINT `FK_MEDICO_fk_medico_solic`
  FOREIGN KEY (`fk_medico_solic`)
  REFERENCES `MEDICO` (`id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE,
ADD CONSTRAINT `FK_MEDICO_fk_medico_dest`
  FOREIGN KEY (`fk_medico_dest`)
  REFERENCES `MEDICO` (`id`)
  ON DELETE CASCADE
  ON UPDATE CASCADE;


